### PR TITLE
Feature/HU200-create-header-footer

### PR DESCRIPTION
**Pull request by caheras**
### Header Description
The header of the webpage is designed with a clean and functional layout. It includes the company logo positioned on the left, a central search bar for easy navigation, and user account links on the right. The account section includes icons and text for "My Account" and "My Cart," with a divider in between. The header is complemented by a subheader below, featuring a horizontal navigation menu with categories such as Technology, Appliances, Mobile Devices, and Home. Each menu item reveals a dropdown submenu on hover, providing users with quick access to related products and services.

### Footer Description
The footer is divided into two main sections. The upper section (footer-middle) displays the company’s social media links and accepted payment methods, along with the business information (Social reason: Ignis & Associates, NIT: 890.900.943-1). Below this, the bottom section (footer-bottom) serves as the sitemap, organized into four columns: "Our Company," "Online Shopping," "Services," and "Policies." Each column contains relevant links, providing users with easy access to important information and services. The footer is finished with a centered copyright notice at the very bottom, ensuring a professional and user-friendly design.

image

Preview on Samsung Galaxy Z Fold 5
image

### CODE REVIEW

**Review by gdgalvis — APPROVED** [review]
Try checking the cart-icon.svg for an unexpected user-like shape in the background. Try to use more of HTML5 tags like sections, but otherwise the page and the code seems good.

**Review by Jcoll05 — APPROVED** [review]
It looks really good.

**Comment by ana03ap** [comment]
It's seems great

**Review by ana03ap — APPROVED** [review]
it's seems great!

**Pull request merged**
